# Generated by Django 4.2.3 on 2023-07-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0002_alter_airplanetype_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="crews",
            field=models.ManyToManyField(blank=True, to="airport.crew"),
        ),
    ]
