# Generated by Django 4.2.3 on 2023-07-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0005_payment_date_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airport",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
